services:
  database: 
    image: postgres:17.5
    env_file:
      - .env
    ports:
      - "5432:5432"
  webapp:
    depends_on:
      - database
    build:
      context: .
      dockerfile: src/entrypoints/webapp/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env