"""added columns for groups

Revision ID: 9bec1b8d7e37
Revises: a745e4ce0717
Create Date: 2025-05-17 15:28:17.571053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bec1b8d7e37'
down_revision: Union[str, None] = 'a745e4ce0717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('type', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'chat_id')
    op.drop_column('chats', 'type')
    # ### end Alembic commands ###
