"""init

Revision ID: ef59abec9ae2
Revises: 
Create Date: 2025-05-17 15:41:43.958938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef59abec9ae2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('groups', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
